openapi: 3.0.1
info:
  title: Imagery Data API
  description: API for retrieving imagery data related to geographic locations.
  version: 1.0.0
servers:
  - url: http://localhost:4000
    description: Local server

paths:
  /search:
    get:
      summary: Search captures based on a location point
      description: Search for captures at a specific latitude and longitude.
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
            example: 37.7749
          description: Latitude of the location point.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
            example: -122.4194
          description: Longitude of the location point.
      responses:
        '200':
          description: Successful search for captures
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    captureId:
                      type: string
                      example: CAP12345
                    location:
                      type: object
                      properties:
                        lat:
                          type: number
                          format: float
                          example: 37.7749
                        lon:
                          type: number
                          format: float
                          example: -122.4194
                    captureDate:
                      type: string
                      format: date-time
                      example: 2023-11-08T10:15:30Z
                    resolution:
                      type: string
                      example: "10m"
        '400':
          description: Invalid location parameters
        '500':
          description: Server error

  /archive:
    get:
      summary: Query recent captures from the archive
      description: Returns the most recent captures from the archive that intersect with a specific point.
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
            example: 37.7749
          description: Latitude of the location point.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
            example: -122.4194
          description: Longitude of the location point.
      responses:
        '200':
          description: Successful retrieval of recent captures
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: "FeatureCollection"
                  features:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          example: "Feature"
                        geometry:
                          type: object
                          properties:
                            type:
                              type: string
                              example: "Point"
                            coordinates:
                              type: array
                              items:
                                type: number
                              example: [-122.4194, 37.7749]
                        properties:
                          type: object
                          properties:
                            captureId:
                              type: string
                              example: CAP12345
                            captureDate:
                              type: string
                              format: date-time
                              example: 2023-11-08T10:15:30Z
                            resolution:
                              type: string
                              example: "10m"
        '400':
          description: Invalid location parameters
        '500':
          description: Server error

  /opportunities:
    get:
      summary: Get future capture opportunities
      description: Returns future capture opportunities at a specific location.
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
            example: 37.7749
          description: Latitude of the location point.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
            example: -122.4194
          description: Longitude of the location point.
      responses:
        '200':
          description: Successful retrieval of future capture opportunities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    opportunityId:
                      type: string
                      example: OP12345
                    estimatedCaptureDate:
                      type: string
                      format: date-time
                      example: 2023-12-01T08:00:00Z
                    confidence:
                      type: string
                      example: "High"
        '400':
          description: Invalid location parameters
        '500':
          description: Server error

